sudo: required
dist: trusty
language: node_js
node_js:
  - '10.12.0'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm i -g npm@latest

before_script:
- npm install
- ng build

script: npm run test:headless